---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-virtualbox-tiantian-cn-v1-virtualbox
  failurePolicy: Fail
  name: mvirtualbox.kb.io
  rules:
  - apiGroups:
    - virtualbox.tiantian.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualboxes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-virtualbox-tiantian-cn-v1-virtualbox
  failurePolicy: Fail
  name: vvirtualbox.kb.io
  rules:
  - apiGroups:
    - virtualbox.tiantian.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualboxes
  sideEffects: None
