# permissions for end users to view virtualboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualbox-viewer-role
rules:
- apiGroups:
  - virtualbox.tiantian.cn
  resources:
  - virtualboxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - virtualbox.tiantian.cn
  resources:
  - virtualboxes/status
  verbs:
  - get
