# permissions for end users to edit virtualboxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualbox-editor-role
rules:
- apiGroups:
  - virtualbox.tiantian.cn
  resources:
  - virtualboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - virtualbox.tiantian.cn
  resources:
  - virtualboxes/status
  verbs:
  - get
